apps/user/urls.py
from django.conf.urls import url

from apps.user.views.home import index
from apps.user.views.account import login, register, send_sms, login_sms

urlpatterns = [
    url(r'^login/$', login, name='login'),  # 密码登录
    url(r'^loginsms/$', login_sms, name='login_sms'),  # 短信登录
    url(r'^register/', register, name='register'),
    url(r'^send_sms/', send_sms, name='send_sms'),

    url(r'^$', index, name='index'),


]

myblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.user.urls', namespace='user')),
    url(r'^blog/', include('apps.blog.urls', namespace='blog')),  # 博客管理

    url(r'^captcha/', include('captcha.urls')),  # 验证码
]

user/urls.py
from django.conf.urls import url

from user.views.home import index
from user.views.account import login, register, send_sms, login_sms

urlpatterns = [
    url(r'^login/$', login, name='login'),  # 密码登录
    url(r'^loginsms/$', login_sms, name='login_sms'),  # 短信登录
    url(r'^register/', register, name='register'),
    url(r'^send_sms/', send_sms, name='send_sms'),

    url(r'^$', index, name='index'),


]

apps/user/models.py
from django.db import models

# Create your models here.


class UserInfo(models.Model):
    username = models.CharField(verbose_name='用户名', max_length=32)
    email = models.EmailField(verbose_name='邮箱', max_length=32)
    mobile_phpne = models.CharField(verbose_name='电话', max_length=32)
    password = models.CharField(verbose_name='密码', max_length=100)

    def __str__(self):
        return self.username

apps/user/forms/account.py
from django import forms
from django.core.exceptions import ValidationError
import bcrypt
from django.core.validators import RegexValidator
from django.db.models import Q
from django_redis import get_redis_connection
from captcha.fields import CaptchaField

from user.forms.bootstrap import BootsTrap
from user.models import UserInfo
from myblog.settings import SMS_TEMPLATE
from utils.tencent.sms import send_sms_single


class CaptchaForm(forms.Form):
    captcha = CaptchaField()


class LoginForm(BootsTrap, forms.Form):
    """用户密码登录表单"""
    mobile_phpne = forms.CharField(label='邮箱或手机号')
    password = forms.CharField(label='密码', widget=forms.PasswordInput())

    def clean_mobile_phpne(self):
        mobile = self.cleaned_data['mobile_phpne']
        user_object = UserInfo.objects.filter(Q(mobile_phpne=mobile) | Q(email=mobile)).first()
        if not user_object:
            raise ValidationError('未注册')

        return user_object

    def clean_password(self):
        try:
            # 手机号不可为空
            pwd = self.cleaned_data['mobile_phpne'].password
        except KeyError:
            return
        password = self.cleaned_data['password']

        if not bcrypt.checkpw(password.encode(), pwd.encode()):
            raise ValidationError('用户名或密码错误')

        return password


class LoginSmsForm(BootsTrap, forms.Form):
    """用户短信登录表单"""
    mobile_phpne = forms.CharField(label='手机号', validators=[RegexValidator(r'^1([3|4|5|6|7|8|9])\d{9}', '手机格式错误')])
    code = forms.CharField(label="验证码")

    def clean_mobile_phpne(self):
        mobile = self.cleaned_data['mobile_phpne']
        user_object = UserInfo.objects.filter(mobile_phpne=mobile).first()
        if not user_object:
            raise ValidationError('手机号未注册++')

        return user_object

    def clean_code(self):
        code = self.cleaned_data['code']
        try:
            user_object = self.cleaned_data['mobile_phpne']
        except KeyError:
            raise ValidationError('')

        # 从redis中取数据
        conn = get_redis_connection()
        code_redis = conn.get(user_object.mobile_phpne)
        try:
            code_redis = code_redis.decode()
            if code_redis != code:
                pass
                raise ValidationError('验证码错误')
            pass
            return code
        except AttributeError:
            raise ValidationError('请先获取验证码')


class RegisterForm(BootsTrap, forms.ModelForm):
    """注册表单"""
    email = forms.EmailField(label='邮箱')
    # 自定义表单的正则匹配
    mobile_phpne = forms.CharField(label="手机", required=True, validators=[RegexValidator(r'^1([3|4|5|6|7|8|9])\d{9}', '手机格式错误--'),])
    # 自定义输入框的格式
    password = forms.CharField(label="密码", required=True, min_length=3, max_length=32, widget=forms.PasswordInput())

    password1 = forms.CharField(label="再次输入密码", min_length=3, max_length=32, required=True, widget=forms.PasswordInput())
    code = forms.CharField(label="验证码")

    class Meta:
        model = UserInfo
        fields = ['username', 'email', 'password', 'password1','mobile_phpne',  'code']

    def clean_password(self):
        # 对用户密码加密
        password = self.cleaned_data['password']
        password = bcrypt.hashpw(password.encode(), bcrypt.gensalt())
        return password

    def clean_email(self):
        """验证邮箱是否被注册过"""
        email = self.cleaned_data['email']
        qs = UserInfo.objects.filter(email=email)
        if qs:
            raise ValidationError('邮箱已被注册')
        return email

    def clean_mobile_phpne(self):
        mobile_phpne = self.cleaned_data['mobile_phpne']

        # 查看手机号是否被注册
        qy = UserInfo.objects.filter(mobile_phpne=mobile_phpne)
        if qy:
            raise ValidationError('该手机号已注册')

        return mobile_phpne

    def clean_code(self):
        # 获取数据
        a = self
        try:
            code = self.cleaned_data['code']
            mobile_phpne = self.cleaned_data['mobile_phpne']
        except KeyError:
            raise ValidationError('')

        # 向redis数据库中取出验证码
        conn = get_redis_connection('default')
        redis_code = conn.get(mobile_phpne)

        # 校验数据
        try:
            if code != redis_code.decode():
                raise ValidationError('验证码错误')
        except AttributeError:
            raise ValidationError('请先获取验证码')

        return code

    def clean(self):
        password = self.cleaned_data.get('password', None)
        password1 = self.cleaned_data.get('password1', None)
        if password is None or password1 is None:
            self.add_error('password1', '请输入密码')
        elif not bcrypt.checkpw(password1.encode(), password):
            self.add_error('password1', '两次密码不一致')

        return self.cleaned_data


class SendSmSForm(forms.Form):
    """发送短信表单"""
    mobile_phpne = forms.CharField(label="手机", min_length=11, max_length=11, validators=[RegexValidator(r'^1([3|4|5|6|7|8|9])\d{9}$', '手机格式错误')])

    def __init__(self, request,  *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.request = request

    def clean_mobile_phpne(self):

        mobile_phpne = self.cleaned_data['mobile_phpne']
        tpl = self.request.GET.get('tpl')

        if tpl == 'register':
            # 查看手机号是否被注册
            qy = UserInfo.objects.filter(mobile_phpne=mobile_phpne)
            if qy:
                raise ValidationError('该手机号已注册')
        elif tpl == 'login':
            # 查看手机号是否被注册
            qy = UserInfo.objects.filter(mobile_phpne=mobile_phpne)
            if not qy:
                raise ValidationError('该手机号未注册--')

        # 查看短信模板是否正确

        if not SMS_TEMPLATE.get(tpl):
            raise ValidationError('请求格式错误')

        # 发送短信验证码
        res = send_sms_single(tpl, mobile_phpne)
        if res['result'] != 0:
            raise ValidationError('短信发送失败：{}'.format(res['errmsg']))

        return mobile_phpne

apps/user/forms/bootstrap.py
class BootsTrap(object):
    """bootstrap基类"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, filed in self.fields.items():
            filed.widget.attrs['class'] = 'form__input'
            filed.widget.attrs['placeholder'] = '请输入{}'.format(filed.label)

apps/user/views/account.py
from django.shortcuts import render
from django.http import JsonResponse
from django_redis import get_redis_connection

from apps.user.forms.account import LoginForm, RegisterForm, SendSmSForm, LoginSmsForm, CaptchaForm


# def register(request):
#     return render(request, 'user/register1.html')


def login(request):
    """密码登录"""
    if request.method == 'GET':
        captcha = CaptchaForm()

        return render(request, 'login.html', {'capt': captcha})

    if request.method == 'POST':
        """表单提交"""
        login_form = LoginForm(request.POST)
        capt = CaptchaForm(request.POST)

        if not capt.is_valid():
            return JsonResponse({'status': False, 'error': capt.errors})

        if not login_form.is_valid():
            return JsonResponse({'status': False, 'error': login_form.errors})

        # 在forms中直接写了返回用户模型对象
        user_object = login_form.cleaned_data['mobile_phpne']

        request.session['user_id'] = user_object.id
        request.session.set_expiry(60 * 60 * 24 * 14)

        return JsonResponse({'status': True, 'data': '/'})


def login_sms(request):
    """短信登录"""
    if request.method == 'GET':
        capt = CaptchaForm()

        return render(request, 'login.html', {'capt': capt})

    if request.method == 'POST':
        """表单提交"""
        login_form = LoginSmsForm(request.POST)

        if login_form.is_valid():
            # 获取经过forms处理后的模型对象
            user_object = login_form.cleaned_data['mobile_phpne']
            mobile_phpne = user_object.mobile_phpne

            # 删除redis中的记录
            conn = get_redis_connection()
            conn.delete(mobile_phpne)

            request.session['user_id'] = user_object.id
            request.session.set_expiry(60 * 60 * 24 * 14)

            return JsonResponse({'status': True, 'data': '/'})

        return JsonResponse({'status': False, 'error': login_form.errors})


def register(request):
    """用户注册"""
    if request.method == 'GET':
        # 显示
        return render(request, 'register.html')

    elif request.method == 'POST':
        # 处理提交
        form = RegisterForm(request.POST)
        if not form.is_valid():
            return JsonResponse({'status': False, 'error': form.errors})
        user = form.save()
        conn = get_redis_connection()
        conn.delete(user.mobile_phpne)

        request.session['user_id'] = user.id
        request.session.set_expiry(60*60*24*14)

        return JsonResponse({'status': True, 'data': 'loginsms'})


def send_sms(request):
    """发送验证码"""
    form = SendSmSForm(request, data=request.GET)
    if form.is_valid():
        return JsonResponse({'status': True})
    return JsonResponse({'status': False, 'error': form.errors})

apps/user/views/home.py
from django.shortcuts import render


# /user/
def index(request):
    return render(request, 'index.html')

user/views/account.py
from django.shortcuts import render
from django.http import JsonResponse
from django_redis import get_redis_connection

from user.forms.account import LoginForm, RegisterForm, SendSmSForm, LoginSmsForm, CaptchaForm


# def register(request):
#     return render(request, 'user/register1.html')


def login(request):
    """密码登录"""
    if request.method == 'GET':
        captcha = CaptchaForm()

        return render(request, 'user/login.html', {'capt': captcha})

    if request.method == 'POST':
        """表单提交"""
        login_form = LoginForm(request.POST)
        capt = CaptchaForm(request.POST)

        if not capt.is_valid():
            return JsonResponse({'status': False, 'error': capt.errors})

        if not login_form.is_valid():
            return JsonResponse({'status': False, 'error': login_form.errors})

        # 在forms中直接写了返回用户模型对象
        user_object = login_form.cleaned_data['mobile_phpne']

        request.session['user_id'] = user_object.id
        request.session.set_expiry(60 * 60 * 24 * 14)

        return JsonResponse({'status': True, 'data': '/'})


def login_sms(request):
    """短信登录"""
    if request.method == 'GET':
        capt = CaptchaForm()

        return render(request, 'user/login.html', {'capt': capt})

    if request.method == 'POST':
        """表单提交"""
        login_form = LoginSmsForm(request.POST)

        if login_form.is_valid():
            # 获取经过forms处理后的模型对象
            user_object = login_form.cleaned_data['mobile_phpne']
            mobile_phpne = user_object.mobile_phpne

            # 删除redis中的记录
            conn = get_redis_connection()
            conn.delete(mobile_phpne)

            request.session['user_id'] = user_object.id
            request.session.set_expiry(60 * 60 * 24 * 14)

            return JsonResponse({'status': True, 'data': '/'})

        return JsonResponse({'status': False, 'error': login_form.errors})


def register(request):
    """用户注册"""
    if request.method == 'GET':
        # 显示
        return render(request, 'user/register.html')

    elif request.method == 'POST':
        # 处理提交
        form = RegisterForm(request.POST)
        if not form.is_valid():
            return JsonResponse({'status': False, 'error': form.errors})
        user = form.save()
        conn = get_redis_connection()
        conn.delete(user.mobile_phpne)

        request.session['user_id'] = user.id
        request.session.set_expiry(60*60*24*14)

        return JsonResponse({'status': True, 'data': 'loginsms'})


def send_sms(request):
    """发送验证码"""
    form = SendSmSForm(request, data=request.GET)
    if form.is_valid():
        return JsonResponse({'status': True})
    return JsonResponse({'status': False, 'error': form.errors})

user/views/home.py
from django.shortcuts import render


# /user/
def index(request):
    return render(request, 'user/index.html')

apps/user/templates/user/login.html
{% extends 'user/layout/login_register_basic.html' %}
{% load staticfiles %}

{% block css %}
    <style>
        #smserrmsg{
                position: absolute;
                top: 185px;
                color: red;
            }
        #lerrmsg{
                position: absolute;
                top: 185px;
                color: red;
            }
    </style>
{% endblock %}

{% block content %}
    <div class="main">
            <div class="container a-container" id="a-container">
                <form class="form" id="a-form">
                    <h2 class="form_title title">密码登录</h2>
                    <div class="errmsg" id="lerrmsg"></div>
                    <input id="cid_mobile_phpne" name="mobile_phpne" class="form__input" type="text" placeholder="手机号或邮箱">
                    <input id="cid_password" name="password" class="form__input" type="password" placeholder="密码">
                    <div style="width: 64%; float: left">
                        {{ capt.captcha }}
                    </div>
                    <a class="form__link " onclick="togo_register()">还未注册?</a>
                    <button id="login" class="form__button button">登录</button>
                    {% csrf_token %}
                </form>
            </div>

            <div class="container b-container is-z200 sms_switchover" id="b-container">
                <form class="form" id="b-form">
                    <h2 class="form_title title">手机登录</h2>
                    <div class="errmsg" id="smserrmsg"></div>
                    <input id="lid_mobile_phpne" name="mobile_phpne" class="form__input" type="text" placeholder="手机号">
                    <input id="lid_code" name="code" class="form__input" type="text" placeholder="手机验证码">
                    <div style="width: 60%; padding-top: 5px">
                       <button style="float: left; width: 100px; height: 30px; font-size: 10px; padding-right: 120px; line-height: 10px" id="lbutton_code" class="code_button">点击获取手机验证码</button>
                        <div id="ltime_span" class="form__span" style="width: 50%; margin-top: 10px; float: right;"></div>
                    </div>
                    <a class="form__link" onclick="togo_register()">还未注册?</a>
                    <button id="loginsms" class="form__button button">登录</button>
                    {% csrf_token %}
                </form>
            </div>

            <div class="switch" id="switch-cnt">
                <div class="switch__circle"></div>
                <div class="switch__circle switch__circle--t"></div>
                <div class="switch__container" id="switch-c1">
                    <h2 class="switch__title title">你好朋友 !</h2>
                    <p class="switch__description description">与我们保持联系,请登录您的个人信息</p>
                    <button class="switch__button button switch-btn">密码登录</button>
                </div>
                <div class="switch__container is-hidden" id="switch-c2">
                    <h2 class="switch__title title">你好朋友 !</h2>
                    <p class="switch__description description">输入您的个人信息,并开始与我们沟通</p>
                    <button class="switch__button button switch-btn">手机登录</button>
                </div>
            </div>

        </div>
{% endblock %}

{% block js %}
    <script type="text/javascript">
    function togo_register() {
        location.href = '/register'
    }

    // 登录获取验证码
    $('.code_button').on('click', function lobindClickBtncode() {
            event.preventDefault();
            $('.errmsg').empty()  // 将内容变为空
            // 获取手机号
            varmobile = $('#lid_mobile_phpne').val()
            var that = $('#lbutton_code')
            $.ajax({
                url: "{% url 'user:send_sms' %}",
                type: "GET",
                data: {'mobile_phpne': varmobile, 'tpl': 'login'},
                dataType: "JSON", // 将返回的数据进行josn序列化
                success: function (data) {
                    if (data.status) {
                        var timeo = 60;
                        var timeStop = setInterval(function () {
                            timeo--;
                            if (timeo > 0) {
                                that.css('background', '#9698a1')
                                $('#ltime_span').html('等待' + timeo + 's');
                                that.attr('disabled', 'disabled');//禁止点击
                            } else {
                                timeo = 60;//当减到0时赋值为60
                                that.css('background', '#262728')
                                clearInterval(timeStop);//清除定时器
                                that.removeAttr('disabled');//移除属性，可点击
                                $('#ltime_span').html('');
                            }
                        }, 1000)
                    } else {
                        $.each(data.error, function (key, val) {
                            if (val[0] == '这个字段是必填项。' || val[0] == '这个字段是必须的')
                            {
                                $('#smserrmsg').show().text('请将信息补充完整')
                            }
                            else
                            {
                               $('#smserrmsg').show().text(val[0])
                            }

                        })
                    }
                },
            })



    }
    )

    // 短信登录
    $('#loginsms').on('click', function (event) {
        event.preventDefault();
        var data = $('#b-form').serializeArray();
        $.post('{% url 'user:login_sms' %}', data, function (data) {
            // 返回结果
            if (data.status) {
                location.href = data.data
            } else {
                $.each(data.error, function (key, val) {
                    if (val[0] == '这个字段是必填项。' || val[0] == '这个字段是必须的')
                            {
                                $('#smserrmsg').show().text('请将信息补充完整')
                            }
                            else
                            {
                               $('#smserrmsg').show().text(val[0])
                            }
                    }
                )
            }
        })

    })

    // 调用刷新按钮
    $('.captcha').click(refresh_capt)

    // 密码登录
    $('#login').on('click', function (event) {
        event.preventDefault();
        var data = $('#a-form').serializeArray();
        console.log(data)
        $.post('{% url 'user:login' %}', data, function (data) {
            // 返回结果
            if (data.status) {
                location.href = data.data
            } else {
                $.each(data.error, function (key, val) {
                        if (val[0] == '这个字段是必填项。' || val[0] == '这个字段是必须的')
                        {
                            $('#lerrmsg').show().text('请将信息补充完整')
                        }
                        else
                        {
                           $('#lerrmsg').show().text(val[0])
                        }

                    }
                )
                refresh_capt()
            }
        })

    })

    // 刷新验证码
    function refresh_capt() {
        $.getJSON("/captcha/refresh/", function (result) {
                $('.captcha').attr('src', result['image_url']);
                $('#id_captcha_0').val(result['key'])
            });
    }

    </script>

{% endblock %}

apps/user/templates/user/register.html
{% extends 'user/layout/login_register_basic.html' %}
{% load staticfiles %}

{% block css %}
    <style>
        #errmsg{
                position: absolute;
                top: 120px;
                color: red;
            }
    </style>
{% endblock %}

{% block content %}
    <div class="main">
            <div class="container a-container" id="a-container">
                <form class="form" id="a-form">
                    <h2 class="form_title title">创建账号</h2>
                    <!-- 第三方登录
                    <div class="form__icons"><img class="form__icon" ><img class="form__icon" ></div><span class="form__span">or use email for registration</span>
                    -->
                    <div style="color: red" class="errmsg" id="errmsg"></div>
                    <input id="id_username" name="username" class="form__input" type="text" placeholder="用户名">
                    <input id="id_email" name="email" class="form__input" type="text" placeholder="Email">
                    <input id="id_password" name="password" class="form__input" type="password" placeholder="密码">
                    <input id="id_password1" name="password1" class="form__input" type="password" placeholder="再次输入密码">
                    <input id="id_mobile_phpne" name="mobile_phpne" class="form__input" type="text" placeholder="手机号">
                    <input id="id_code" name="code" class="form__input" type="text" placeholder="手机验证码">
                    <div style="width: 60%; padding-top: 5px">
                       <button style="float: left; width: 100px; height: 30px; font-size: 10px; padding-right: 120px; line-height: 10px" id="button_code" class="code_button" onclick="rebindClickBtncode()">点击获取手机验证码</button>
                        <div id="time_span" class="form__span" style="width: 50%; margin-top: 10px; float: right;"></div>
                    </div>

                    <button  id="register" class="form__button button">立即注册</button>
                    {% csrf_token %}
                </form >

            </div>
            <div class="switch" id="switch-cnt">
                <div class="switch__circle"></div>
                <div class="switch__circle switch__circle--t"></div>
                <div class="switch__container" id="switch-c1">
                    <h2 class="switch__title title">欢迎回来 !</h2>
                    <p class="switch__description description">与我们保持联系,请登录您的个人信息</p>
                    <button class="switch__button button" onclick="goto_login()">立即登录</button>
                </div>
            </div>
        </div>
{% endblock %}

{% block js %}
    <script>
        function goto_login() {
            location.href = '/login'
        }
    </script>
    <script>
        // 注册获取验证码
        function rebindClickBtncode() {
                event.preventDefault();
                $('.errmsg').empty()  // 将内容变为空
                // 获取手机号
                varmobile = $('#id_mobile_phpne').val()
                var that = $('#button_code')
                $.ajax({
                    url: "{% url 'user:send_sms' %}",
                    type: "GET",
                    data: {'mobile_phpne': varmobile, 'tpl': 'register'},
                    dataType: "JSON", // 将返回的数据进行josn序列化
                    success: function (data) {
                        if (data.status) {
                            var timeo = 60;
                            var timeStop = setInterval(function () {
                                timeo--;
                                if (timeo > 0) {
                                    that.css('background', '#9698a1')
                                    $('#time_span').html('等待' + timeo + 's');
                                    that.attr('disabled', 'disabled');//禁止点击
                                } else {
                                    timeo = 60;//当减到0时赋值为60
                                    that.css('background', '#262728')
                                    clearInterval(timeStop);//清除定时器
                                    that.removeAttr('disabled');//移除属性，可点击
                                    $('#time_span').html('');
                                }
                            }, 1000)
                        } else {
                            $.each(data.error, function (key, val) {
                                if (val[0] == '这个字段是必填项。' || val[0] == '这个字段是必须的')
                                {
                                    $('#errmsg').show().text('请将信息补充完整')
                                }
                                else
                                {
                                   $('#errmsg').show().text(val[0])
                                }

                            })
                        }
                    },
                })



        }

        // 注册
        $('#register').on('click', function () {
        event.preventDefault();
        var data = $('#a-form').serialize();
        $.post('{% url 'user:register' %}', data, function (data) {
            // 返回结果
            if (data.status) {
                location.href = '/web/' + data.data
            } else {
                $.each(data.error, function (key, val) {
                    if (val[0] == '这个字段是必填项。' || val[0] == '这个字段是必须的')
                    {
                        $('#errmsg').show().text('请将信息补充完整')
                    }
                    else
                    {
                       $('#errmsg').show().text(val[0])
                    }
                }
                )
            }
        })
    })
    </script>


{% endblock %}