apps/blog/urls.py
from django.conf.urls import url

from apps.blog.views import Blog, AddBlog


urlpatterns = [
    url(r'^add', AddBlog.as_view(), name='add_blog'),  # 博客页展示
    url(r'^', Blog.as_view(), name='blog'),  # 博客页展示

]

myblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.user.urls', namespace='user')),
    url(r'^blog/', include('apps.blog.urls', namespace='blog')),  # 博客管理

    url(r'^captcha/', include('captcha.urls')),  # 验证码
]

user/urls.py
from django.conf.urls import url

from user.views.home import index
from user.views.account import login, register, send_sms, login_sms

urlpatterns = [
    url(r'^login/$', login, name='login'),  # 密码登录
    url(r'^loginsms/$', login_sms, name='login_sms'),  # 短信登录
    url(r'^register/', register, name='register'),
    url(r'^send_sms/', send_sms, name='send_sms'),

    url(r'^$', index, name='index'),


]

apps/blog/models.py
from django.db import models

from db.base_model import BaseModel

# Create your models here.


class BlogTypeModel(BaseModel):
    """博客分类"""
    title = models.CharField(verbose_name='标题', max_length=100)
    index = models.SmallIntegerField(verbose_name='优先级', default=0)

    def __str__(self):
        return self.title


class BlogTagModel(BaseModel):
    """博文标签"""
    lable = models.CharField(verbose_name='标题', max_length=100)

    def __str__(self):
        return self.lable


class BlogModel(BaseModel):
    """博文类"""
    title = models.CharField(verbose_name='标题', max_length=100)
    image = models.ImageField(verbose_name='博客标图', null=True, blank=True, upload_to="blog/%Y/%m", max_length=100)
    intro = models.CharField(verbose_name='简介', max_length=100)
    context = models.TextField(verbose_name='内容')
    # tag = models.ManyToManyField(verbose_name='标签', to='BlogTagModel')
    read_count = models.PositiveIntegerField(verbose_name='阅读量')
    comment_count = models.PositiveIntegerField(verbose_name='评论量')
    like_count = models.PositiveIntegerField(verbose_name='点赞量')
    blog_type = models.ForeignKey(verbose_name='博文分类', to='BlogTypeModel', default='2')
    BLOG_CLS_CHOICES = (
        (1, '原创'),
        (2, '转载'),
    )
    blog_cls = models.SmallIntegerField(verbose_name='博文类型', choices=BLOG_CLS_CHOICES, default=1)

    creator = models.ForeignKey(verbose_name='创作者', to='user.UserInfo')
    hint = models.CharField(verbose_name='文章备注', max_length=300)

apps/user/models.py
from django.db import models

# Create your models here.


class UserInfo(models.Model):
    username = models.CharField(verbose_name='用户名', max_length=32)
    email = models.EmailField(verbose_name='邮箱', max_length=32)
    mobile_phpne = models.CharField(verbose_name='电话', max_length=32)
    password = models.CharField(verbose_name='密码', max_length=100)

    def __str__(self):
        return self.username

apps/user/forms/account.py
from django import forms
from django.core.exceptions import ValidationError
import bcrypt
from django.core.validators import RegexValidator
from django.db.models import Q
from django_redis import get_redis_connection
from captcha.fields import CaptchaField

from user.forms.bootstrap import BootsTrap
from user.models import UserInfo
from myblog.settings import SMS_TEMPLATE
from utils.tencent.sms import send_sms_single


class CaptchaForm(forms.Form):
    captcha = CaptchaField()


class LoginForm(BootsTrap, forms.Form):
    """用户密码登录表单"""
    mobile_phpne = forms.CharField(label='邮箱或手机号')
    password = forms.CharField(label='密码', widget=forms.PasswordInput())

    def clean_mobile_phpne(self):
        mobile = self.cleaned_data['mobile_phpne']
        user_object = UserInfo.objects.filter(Q(mobile_phpne=mobile) | Q(email=mobile)).first()
        if not user_object:
            raise ValidationError('未注册')

        return user_object

    def clean_password(self):
        try:
            # 手机号不可为空
            pwd = self.cleaned_data['mobile_phpne'].password
        except KeyError:
            return
        password = self.cleaned_data['password']

        if not bcrypt.checkpw(password.encode(), pwd.encode()):
            raise ValidationError('用户名或密码错误')

        return password


class LoginSmsForm(BootsTrap, forms.Form):
    """用户短信登录表单"""
    mobile_phpne = forms.CharField(label='手机号', validators=[RegexValidator(r'^1([3|4|5|6|7|8|9])\d{9}', '手机格式错误')])
    code = forms.CharField(label="验证码")

    def clean_mobile_phpne(self):
        mobile = self.cleaned_data['mobile_phpne']
        user_object = UserInfo.objects.filter(mobile_phpne=mobile).first()
        if not user_object:
            raise ValidationError('手机号未注册++')

        return user_object

    def clean_code(self):
        code = self.cleaned_data['code']
        try:
            user_object = self.cleaned_data['mobile_phpne']
        except KeyError:
            raise ValidationError('')

        # 从redis中取数据
        conn = get_redis_connection()
        code_redis = conn.get(user_object.mobile_phpne)
        try:
            code_redis = code_redis.decode()
            if code_redis != code:
                pass
                raise ValidationError('验证码错误')
            pass
            return code
        except AttributeError:
            raise ValidationError('请先获取验证码')


class RegisterForm(BootsTrap, forms.ModelForm):
    """注册表单"""
    email = forms.EmailField(label='邮箱')
    # 自定义表单的正则匹配
    mobile_phpne = forms.CharField(label="手机", required=True, validators=[RegexValidator(r'^1([3|4|5|6|7|8|9])\d{9}', '手机格式错误--'),])
    # 自定义输入框的格式
    password = forms.CharField(label="密码", required=True, min_length=3, max_length=32, widget=forms.PasswordInput())

    password1 = forms.CharField(label="再次输入密码", min_length=3, max_length=32, required=True, widget=forms.PasswordInput())
    code = forms.CharField(label="验证码")

    class Meta:
        model = UserInfo
        fields = ['username', 'email', 'password', 'password1','mobile_phpne',  'code']

    def clean_password(self):
        # 对用户密码加密
        password = self.cleaned_data['password']
        password = bcrypt.hashpw(password.encode(), bcrypt.gensalt())
        return password

    def clean_email(self):
        """验证邮箱是否被注册过"""
        email = self.cleaned_data['email']
        qs = UserInfo.objects.filter(email=email)
        if qs:
            raise ValidationError('邮箱已被注册')
        return email

    def clean_mobile_phpne(self):
        mobile_phpne = self.cleaned_data['mobile_phpne']

        # 查看手机号是否被注册
        qy = UserInfo.objects.filter(mobile_phpne=mobile_phpne)
        if qy:
            raise ValidationError('该手机号已注册')

        return mobile_phpne

    def clean_code(self):
        # 获取数据
        a = self
        try:
            code = self.cleaned_data['code']
            mobile_phpne = self.cleaned_data['mobile_phpne']
        except KeyError:
            raise ValidationError('')

        # 向redis数据库中取出验证码
        conn = get_redis_connection('default')
        redis_code = conn.get(mobile_phpne)

        # 校验数据
        try:
            if code != redis_code.decode():
                raise ValidationError('验证码错误')
        except AttributeError:
            raise ValidationError('请先获取验证码')

        return code

    def clean(self):
        password = self.cleaned_data.get('password', None)
        password1 = self.cleaned_data.get('password1', None)
        if password is None or password1 is None:
            self.add_error('password1', '请输入密码')
        elif not bcrypt.checkpw(password1.encode(), password):
            self.add_error('password1', '两次密码不一致')

        return self.cleaned_data


class SendSmSForm(forms.Form):
    """发送短信表单"""
    mobile_phpne = forms.CharField(label="手机", min_length=11, max_length=11, validators=[RegexValidator(r'^1([3|4|5|6|7|8|9])\d{9}$', '手机格式错误')])

    def __init__(self, request,  *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.request = request

    def clean_mobile_phpne(self):

        mobile_phpne = self.cleaned_data['mobile_phpne']
        tpl = self.request.GET.get('tpl')

        if tpl == 'register':
            # 查看手机号是否被注册
            qy = UserInfo.objects.filter(mobile_phpne=mobile_phpne)
            if qy:
                raise ValidationError('该手机号已注册')
        elif tpl == 'login':
            # 查看手机号是否被注册
            qy = UserInfo.objects.filter(mobile_phpne=mobile_phpne)
            if not qy:
                raise ValidationError('该手机号未注册--')

        # 查看短信模板是否正确

        if not SMS_TEMPLATE.get(tpl):
            raise ValidationError('请求格式错误')

        # 发送短信验证码
        res = send_sms_single(tpl, mobile_phpne)
        if res['result'] != 0:
            raise ValidationError('短信发送失败：{}'.format(res['errmsg']))

        return mobile_phpne

templates/index.html
{#{% load static %}#}

<!DOCTYPE html>
{% load staticfiles %}
<html lang="zh-Hans-CN">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width" />
    <title>首页</title>
    <link href="{% static 'layui/css/layui.css' %}" rel="stylesheet" >
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" >
    <link href="{% static 'css/index_style.css' %}" rel="stylesheet" >
    <link href="{% static 'css/animate.min.css' %}" rel="stylesheet" >

</head>
<body>
    <div id="menu" class="hover_animation menu_open" data-mark="false">
        <span></span>
        <span></span>
        <span></span>
    </div>
    <div id="navgation" class="navgation navgation_close">
        <ul class="point">
            <li><a href="{% url 'user:index' %}">首页</a></li>
            <li><a href="{% url 'blog:blog'%}">博客</a></li>
{#            <li><a href="message.html">留言</a></li>#}
            <li><a href="{% url 'user:login_sms' %}">登录</a></li>
        </ul>
        <div class="logo"><a>R.Lei</a></div>
    </div>
    <div class="section" id="section1">
        <div class="fp-tablecell">
            <div class="page1">
                <div class="nav wow zoomIn" data-wow-duration="2s">
                    <h1>任三石</h1>
                    <p>用自己拼一个可能，回敬所有人说的不可能</p>
                    <a class="layui-btn layui-btn-normal" style="margin-top: 20px" href="#">Enter Blog</a>
                </div>
                <a class="next wow fadeInUp" data-wow-duration="2s" id="next"></a>
            </div>
        </div>
    </div>
    <div class="section" id="section2">
        <div class="fp-tablecell">
            <div class="page2">
                <div class="warp-box">
                    <div class="new-article">
                        <div class="inner wow fadeInDown" data-wow-delay=".2s">
                            <h1>热门文章</h1>
                            <p>
                                很想给你写封信,告诉你这里的天气.
                                <br>昨夜的那场电影,还有我的心情.
                            </p>
                        </div>
                    </div>
                    <div class="layui-row">
                        <div class="layui-col-xs12 layui-col-sm4 layui-col-md4  wow fadeInUp" style="padding: 0 10px">
                            <div class="single-news">
                                <div class="news-head">
                                    <img src="{% static 'image/1.jpg' %}">
                                    <a href="#" class="link"><i class="fa fa-link"></i></a>
                                </div>
                                <div class="news-content">
                                    <h4>
                                        <a href="#">
                                            标题
                                        </a>
                                    </h4>
                                    <div class="date">
                                        2017年2月16日
                                    </div>
                                    <p>
                                        很想给你写封信,告诉你这里的天气. 昨夜的那场电影,还有我的心情.
                                    </p>
                                    <a href="#" class="btn">
                                        阅读更多
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="layui-col-xs12 layui-col-sm4 layui-col-md4  wow fadeInUp" data-wow-delay=".2s" style="padding: 0 10px">
                            <div class="single-news">
                                <div class="news-head">
                                    <img src="{% static 'image/1.jpg' %}">
                                    <a href="#" class="link"><i class="fa fa-link"></i></a>
                                </div>
                                <div class="news-content">
                                    <h4>
                                        <a href="#">
                                            标题
                                        </a>
                                    </h4>
                                    <div class="date">
                                        2017年2月16日
                                    </div>
                                    <p>
                                        很想给你写封信,告诉你这里的天气. 昨夜的那场电影,还有我的心情.
                                    </p>
                                    <a href="#" class="btn">
                                        阅读更多
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="layui-col-xs12 layui-col-sm4 layui-col-md4  wow fadeInUp" data-wow-delay=".4s" style="padding: 0 10px">
                            <div class="single-news">
                                <div class="news-head">
                                    <img src="{% static 'image/1.jpg' %}">
                                    <a href="#" class="link"><i class="fa fa-link"></i></a>
                                </div>
                                <div class="news-content">
                                    <h4>
                                        <a href="#">
                                            标题
                                        </a>
                                    </h4>
                                    <div class="date">
                                        2017年2月16日
                                    </div>
                                    <p>
                                        很想给你写封信,告诉你这里的天气. 昨夜的那场电影,还有我的心情.
                                    </p>
                                    <a href="#" class="btn">
                                        阅读更多
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="section" id="section3">
        <div class="fp-tablecell">
            <div class="page3">
                <div class="warp-box">
                    <div class="warp">
                        <div class="inner">
                            <div class="links">
                                <ul>
                                    <li class="wow fadeInLeft"><a href="#">关于</a></li>
                                    <li class="wow fadeInRight"><a href="#">+友情链接</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="section" id="section4">
        <div class="fp-tablecell">
            <div class="page4">
                <div class="warp-box">
                    <div class="about">
                        <div class="inner">
                            <h1 class="wow fadeInLeft">次元使者</h1>
                            <p class="wow fadeInRight">
                                爱好游戏，动漫。闲来无事喜欢在一些不健康的场所虚度光阴，撸起代码就会废寝忘食。
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <footer class="footer wow fadeInUp" id="contact">
        <div class="footer-top">
            <div class="container">
                <div class="layui-row">
                    <div class="layui-col-xs12 layui-col-sm6 layui-col-md4">
                        <div class="single-widget about">
                            <div class="footer-logo">
                                <h2>燕十三</h2>
                            </div>
                            <p>剑气纵横三万里，一剑光寒十九洲。</p>
                            <div class="button">
                                <a href="#" class="btn layui-btn layui-btn-normal">About Me</a>
                            </div>
                        </div>
                    </div>
                    <div class="layui-col-xs12 layui-col-sm6 layui-col-md4">
                        <div class="single-widget">
                            <h2>相关链接</h2>
                            <ul class="social-icon">
                                <li class="active"><a href="#"><i class="fa fa-book"></i>博文</a></li>
                                <li class="active"><a href="#"><i class="fa fa-comments"></i>留言</a></li>
                                <li class="active"><a href="#"><i class="fa fa-share"></i>资源</a></li>
                                <li class="active"><a href="#"><i class="fa fa-snowflake-o"></i>日记</a></li>
                                <li class="active"><a href="#"><i class="fa fa-files-o"></i>归档</a></li>
                            </ul>                   
                        </div>
                    </div>
                    <div class="layui-col-xs12 layui-col-sm12 layui-col-md4">
                        <div class="single-widget contact">
                            <h2>联系我</h2>
                            <ul class="list">
                                <li><i class="fa fa-map"></i>地址: 四川成都金牛区金科北路39号</li>
                                <li><i class="fa fa-qq"></i>QQ: 930054439 </li>
                                <li><i class="fa fa-envelope"></i>邮箱: 930054439@qq.com</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="copyright">
            <div class="container">
                <div class="layui-row">
                    <div class="layui-col-xs12 layui-col-sm12 layui-col-md12 text-center">
                        <p>Copyright &copy; 2018-2018 燕十三 All Rights Reserved V.3.1.3 蜀ICP备18008600号</p>
                    </div>
                </div>
            </div>
        </div>  
    </footer>
    <script src="{% static 'layui/layui.js' %}"></script>
    <script src="{% static 'js/wow.min.js' %}"></script>
    <script src="{% static 'js/index.js' %} "></script>
</body>
</html>

templates/register.html
{% extends 'layout/login_register_basic.html' %}
{% load staticfiles %}

{% block css %}
    <style>
        #errmsg{
                position: absolute;
                top: 120px;
                color: red;
            }
    </style>
{% endblock %}

{% block content %}
    <div class="main">
            <div class="container a-container" id="a-container">
                <form class="form" id="a-form">
                    <h2 class="form_title title">创建账号</h2>
                    <!-- 第三方登录
                    <div class="form__icons"><img class="form__icon" ><img class="form__icon" ></div><span class="form__span">or use email for registration</span>
                    -->
                    <div style="color: red" class="errmsg" id="errmsg"></div>
                    <input id="id_username" name="username" class="form__input" type="text" placeholder="用户名">
                    <input id="id_email" name="email" class="form__input" type="text" placeholder="Email">
                    <input id="id_password" name="password" class="form__input" type="password" placeholder="密码">
                    <input id="id_password1" name="password1" class="form__input" type="password" placeholder="再次输入密码">
                    <input id="id_mobile_phpne" name="mobile_phpne" class="form__input" type="text" placeholder="手机号">
                    <input id="id_code" name="code" class="form__input" type="text" placeholder="手机验证码">
                    <div style="width: 60%; padding-top: 5px">
                       <button style="float: left; width: 100px; height: 30px; font-size: 10px; padding-right: 120px; line-height: 10px" id="button_code" class="code_button" onclick="rebindClickBtncode()">点击获取手机验证码</button>
                        <div id="time_span" class="form__span" style="width: 50%; margin-top: 10px; float: right;"></div>
                    </div>

                    <button  id="register" class="form__button button">立即注册</button>
                    {% csrf_token %}
                </form >

            </div>
            <div class="switch" id="switch-cnt">
                <div class="switch__circle"></div>
                <div class="switch__circle switch__circle--t"></div>
                <div class="switch__container" id="switch-c1">
                    <h2 class="switch__title title">欢迎回来 !</h2>
                    <p class="switch__description description">与我们保持联系,请登录您的个人信息</p>
                    <button class="switch__button button" onclick="goto_login()">立即登录</button>
                </div>
            </div>
        </div>
{% endblock %}

{% block js %}
    <script>
        function goto_login() {
            location.href = '/login'
        }
    </script>
    <script>
        // 注册获取验证码
        function rebindClickBtncode() {
                event.preventDefault();
                $('.errmsg').empty()  // 将内容变为空
                // 获取手机号
                varmobile = $('#id_mobile_phpne').val()
                var that = $('#button_code')
                $.ajax({
                    url: "{% url 'user:send_sms' %}",
                    type: "GET",
                    data: {'mobile_phpne': varmobile, 'tpl': 'register'},
                    dataType: "JSON", // 将返回的数据进行josn序列化
                    success: function (data) {
                        if (data.status) {
                            var timeo = 60;
                            var timeStop = setInterval(function () {
                                timeo--;
                                if (timeo > 0) {
                                    that.css('background', '#9698a1')
                                    $('#time_span').html('等待' + timeo + 's');
                                    that.attr('disabled', 'disabled');//禁止点击
                                } else {
                                    timeo = 60;//当减到0时赋值为60
                                    that.css('background', '#262728')
                                    clearInterval(timeStop);//清除定时器
                                    that.removeAttr('disabled');//移除属性，可点击
                                    $('#time_span').html('');
                                }
                            }, 1000)
                        } else {
                            $.each(data.error, function (key, val) {
                                if (val[0] == '这个字段是必填项。' || val[0] == '这个字段是必须的')
                                {
                                    $('#errmsg').show().text('请将信息补充完整')
                                }
                                else
                                {
                                   $('#errmsg').show().text(val[0])
                                }

                            })
                        }
                    },
                })



        }

        // 注册
        $('#register').on('click', function () {
        event.preventDefault();
        var data = $('#a-form').serialize();
        $.post('{% url 'user:register' %}', data, function (data) {
            // 返回结果
            if (data.status) {
                location.href = '/web/' + data.data
            } else {
                $.each(data.error, function (key, val) {
                    if (val[0] == '这个字段是必填项。' || val[0] == '这个字段是必须的')
                    {
                        $('#errmsg').show().text('请将信息补充完整')
                    }
                    else
                    {
                       $('#errmsg').show().text(val[0])
                    }
                }
                )
            }
        })
    })
    </script>


{% endblock %}

templates/write_blog.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form method="post">

        {% csrf_token %}
        {{ form }}
        <button type="submit">提交</button>
    </form>

</body>
</html>